"""Adds economy columns to users table

Revision ID: 02f954917a1c
Revises: c585cf5a5290
Create Date: 2020-05-28 23:55:52.046308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f954917a1c'
down_revision = 'c585cf5a5290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('money', sa.Numeric(precision=4), nullable=True))
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xp')
    op.drop_column('users', 'money')
    op.drop_column('users', 'level')
    # ### end Alembic commands ###
