"""Adds reminders table

Revision ID: 36e6f775e94c
Revises: 2b1b28f2334d
Create Date: 2020-04-11 00:28:56.487521

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '36e6f775e94c'
down_revision = '2b1b28f2334d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
