"""Test Migration

Revision ID: 3cb1da24dbed
Revises: 904e14c2edcb
Create Date: 2020-04-08 22:34:01.949862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb1da24dbed'
down_revision = '904e14c2edcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guilds')
    # ### end Alembic commands ###
