"""database relations rework

Revision ID: 4005142cb594
Revises: 75892e480038
Create Date: 2020-05-13 23:28:33.202448

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4005142cb594"
down_revision = "75892e480038"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("reminders_guild_id_fkey", "reminders", type_="foreignkey")
    op.drop_column("reminders", "guild_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reminders",
        sa.Column("guild_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "reminders_guild_id_fkey", "reminders", "guilds", ["guild_id"], ["id"]
    )
    # ### end Alembic commands ###
