"""Adds daily cooldown to Users

Revision ID: 4d9184d6f3a6
Revises: 7a51949f72cd
Create Date: 2020-05-30 03:05:22.555733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9184d6f3a6'
down_revision = '7a51949f72cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_cooldown', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_cooldown')
    # ### end Alembic commands ###
