"""empty message

Revision ID: 50425320898b
Revises: 1623f7ae0dfb
Create Date: 2020-05-13 02:36:32.279369

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "50425320898b"
down_revision = "1623f7ae0dfb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("guild_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("birthday", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
        sa.UniqueConstraint("user_id", "guild_id", name="guild_user"),
    )
    # ### end Alembic commands ###
