"""Add Economy

Revision ID: 611c4cd8d920
Revises: 82015d1876e6
Create Date: 2020-11-06 21:18:13.075674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "611c4cd8d920"
down_revision = "82015d1876e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("daily_streak", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("last_daily", sa.TIMESTAMP(), nullable=True))
    op.add_column("users", sa.Column("level", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("money", sa.Numeric(precision=4), nullable=True))
    op.add_column("users", sa.Column("xp", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "xp")
    op.drop_column("users", "money")
    op.drop_column("users", "level")
    op.drop_column("users", "last_daily")
    op.drop_column("users", "daily_streak")
    # ### end Alembic commands ###
