"""Move model to other file

Revision ID: 6846673cde7e
Revises: 3cb1da24dbed
Create Date: 2020-04-08 22:34:32.031526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6846673cde7e'
down_revision = '3cb1da24dbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guilds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prefix', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='guilds_pkey')
    )
    # ### end Alembic commands ###
