"""database relations rework

Revision ID: 75892e480038
Revises: c34a3d8f38fb
Create Date: 2020-05-13 23:28:20.221493

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "75892e480038"
down_revision = "c34a3d8f38fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reminders", sa.Column("guild_id", sa.BIGINT(), nullable=True))
    op.create_foreign_key(None, "reminders", "guilds", ["guild_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reminders", type_="foreignkey")
    op.drop_column("reminders", "guild_id")
    # ### end Alembic commands ###
