"""users table default values

Revision ID: 7a51949f72cd
Revises: 02f954917a1c
Create Date: 2020-05-29 00:01:18.223483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a51949f72cd'
down_revision = '02f954917a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
