"""Initial Revision

Revision ID: 82015d1876e6
Revises: 
Create Date: 2020-11-05 22:29:10.053547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "82015d1876e6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guilds",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("prefix", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guilds")),
    )
    op.create_table(
        "emotes",
        sa.Column("guild_id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["guild_id"], ["guilds.id"], name=op.f("fk_emotes_guild_id_guilds")
        ),
        sa.PrimaryKeyConstraint("guild_id", "name", name="guild_id_emote"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=True),
        sa.Column("guild_id", sa.BIGINT(), nullable=True),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["guild_id"], ["guilds.id"], name=op.f("fk_users_guild_id_guilds")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("user_id", "guild_id", name="guild_user"),
    )
    op.create_table(
        "polls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("due_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("message_id", sa.BIGINT(), nullable=True),
        sa.Column("options", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("channel_id", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["users.id"], name=op.f("fk_polls_creator_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_polls")),
    )
    op.create_table(
        "reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("due_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("reminder", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("channel_id", sa.BIGINT(), nullable=True),
        sa.Column("send_dm", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_reminders_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminders")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reminders")
    op.drop_table("polls")
    op.drop_table("users")
    op.drop_table("emotes")
    op.drop_table("guilds")
    # ### end Alembic commands ###
