"""Initial migration

Revision ID: 904e14c2edcb
Revises: 
Create Date: 2020-04-08 22:31:56.354995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904e14c2edcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
