"""Adds reminders table

Revision ID: a4f930629672
Revises: 36e6f775e94c
Create Date: 2020-04-11 00:30:20.021187

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a4f930629672'
down_revision = '36e6f775e94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('due_time', sa.Time(), nullable=True),
    sa.Column('reminder', sa.String(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('channel_id', sa.BIGINT(), nullable=True),
    sa.Column('guild_id', sa.BIGINT(), nullable=True),
    sa.Column('send_dm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    # ### end Alembic commands ###
