"""adds polls table

Revision ID: c585cf5a5290
Revises: 4005142cb594
Create Date: 2020-05-18 23:18:12.113125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c585cf5a5290'
down_revision = '4005142cb594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('due_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('message_id', sa.BIGINT(), nullable=True),
    sa.Column('options', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polls')
    # ### end Alembic commands ###
