"""change due_time to tiemstamp

Revision ID: cbee5d733861
Revises: a4f930629672
Create Date: 2020-04-14 21:38:30.472021

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cbee5d733861'
down_revision = 'a4f930629672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
