"""Adds emotes table

Revision ID: e877446e82ec
Revises: cbee5d733861
Create Date: 2020-05-09 18:49:07.839590

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e877446e82ec"
down_revision = "cbee5d733861"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emotes",
        sa.Column("guild_id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("guild_id", "name", name="guild_id_emote"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("emotes")
    # ### end Alembic commands ###
