"""Change Guild.id to bigint

Revision ID: ef28e4e81976
Revises: 5a16c303f781
Create Date: 2020-04-08 22:52:29.961167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef28e4e81976'
down_revision = '5a16c303f781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
